### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by aviiciii** [Bhavesh38/V-Book-Project#12]
Most of the code in the repository are javascript files and each file is formatted differently.

I suggest to use indentation using tabs to format the code for better vesatility with the developers.

**Comment by aviiciii** [comment]
Pull request #10 has been initiated by me where I have formatted all the files in the frontend directory.

**Comment by aviiciii** [comment]
Pull request #11 has been initiated by me where I have formatted all the files in the backend directory.

**Comment by aviiciii** [comment]
This contribution is under diversion2k22. Kindly add the labels.

**Comment by Vaibhav8090** [comment]
> This contribution is under diversion2k22. Kindly add the labels.

OK
