### ISSUE TITLE
email verification 

### ISSUE THREAD

**Issue by Vaibhav8090** [Bhavesh38/V-Book-Project#2]
we have to work from frontend side for the email verification

**Comment by rt-001** [comment]
I would like to work on this .

**Comment by Vaibhav8090** [comment]
OK WE ARE CURRENTLY WORKING IF YOU ARE FREE THEN JOIN THIS MEETING LINKhttp://meet.google.com/vtj-kruw-qmsOR ELSE YOU CAN CONATCT ME THROUGH WP 8090578488Sent from Mail for Windows From: Romit TiwariSent: 07 February 2023 12:53To: Bhavesh38/V-Book-ProjectCc: VaibhavPatel; AuthorSubject: Re: [Bhavesh38/V-Book-Project] email verification (Issue #2) I would like to work on this .—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> Virus-free.www.avast.com

**Comment by Vaibhav8090** [comment]
OK CAME TO TODAY MEET AT 6 PM OR ELSE YOU CAN CONATCT ME THROUGH DISCORD Vaibhav#3656

**Comment by Vaibhav8090** [comment]
> I would like to work on this .

OK JOIN THE MEET AT 6PM ON DISCORD V BOOK CHANNEL WE WILL EXPLAIN YOU MORE ABOUT THIS
